name: Build & Test

on:
  push:
    branches:
      - main
    
    paths-ignore:
      - "README.md"
      - "**/*.md"

  pull_request:
    
    paths-ignore:
      - "README.md"
      - "**/*.md"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate_mock_data:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requirements
        run: |
          pip install -r scripts/requirements.txt

      - name: Generate fake data
        run: |
          mkdir test_data
          python scripts/generate_mock_data.py test_data/data.parquet 100

      - name: Upload fake data
        uses: actions/upload-artifact@v4
        with:
          name: fake-data
          path: test_data/

  build:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-14
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.os }}
          path: |
            target/release/park
            target/release/park.exe

  e2e_vm:
    needs:
      - generate_mock_data
      - build

    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-14
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: binary-${{ matrix.os }}
          path: bin/

      - name: Download fake data
        uses: actions/download-artifact@v4
        with:
          name: fake-data
          path: test_data/

      - name: Make executable (Linux/macOS)
        if: runner.os != 'Windows'
        run: chmod +x bin/park

      - name: Run E2E tests subcommand info (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          ./bin/park info test_data/data.parquet

      - name: Run E2E tests subcommand info (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ./bin/park.exe info test_data/data.parquet

      - name: Run E2E tests subcommand head (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          ./bin/park head test_data/data.parquet --num 3
          ./bin/park head test_data/data.parquet --num 3 --format csv

      - name: Run E2E tests subcommand head (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ./bin/park.exe head test_data/data.parquet --num 3
          ./bin/park.exe head test_data/data.parquet --num 3 --format csv

      - name: Run E2E tests subcommand tail (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          ./bin/park tail test_data/data.parquet --num 3
          ./bin/park tail test_data/data.parquet --num 3 --format csv

      - name: Run E2E tests subcommand head (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ./bin/park.exe tail test_data/data.parquet --num 3
          ./bin/park.exe tail test_data/data.parquet --num 3 --format csv