name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            artifact: park-linux
            binary: park

          - os: macos-14
            artifact: park-macos
            binary: park

          - os: windows-latest
            artifact: park-windows
            binary: park.exe

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release

      - name: Package (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          mkdir dist
          cp target/release/${{ matrix.binary }} dist/
          tar czf ${{ matrix.artifact }}.tar.gz -C dist .

      - name: Package (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          mkdir dist
          Copy-Item target/release/${{ matrix.binary }} dist/
          Compress-Archive -Path dist/* -DestinationPath "${{ matrix.artifact }}.zip"

      - name: Upload Linux/macOS
        if: runner.os != 'Windows'
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.artifact }}.tar.gz

      - name: Upload Windows
        if: runner.os == 'Windows'
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.artifact }}.zip
  
  install:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
          - os: macos-14
          - os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    
      - name: Install with script ${{ matrix.os }}
        shell: bash
        run: |
          curl -fsSL https://raw.githubusercontent.com/314arhaam/park-rs/main/install.sh | bash
      
      - name: Get Park help ${{ matrix.os }}
        shell: bash
        run: |
          park --help